openapi: 3.0.4
info:
  version: 1.1.0
  title: Activity Records API (Smart System)
  description: The Activity Records API allows riders to query past activities which have been recorded using the eBike Flow app. It provides access to activity details as well as a comprehensive activity summary after a ride is successfully finished.
  contact:
    email: cloud-api.support@de.bosch.com
    name: Bosch eBike Systems Support
servers:
  - url: 'https://api.bosch-ebike.com/activity/smart-system/v1'
    description: Production
paths:
  /activities:
    get:
      tags:
        - Activities
      summary: List all activity summaries
      description: Returns a list of activity summaries associated with a user.
      operationId: get-activities
      parameters:
        - name: offset
          in: query
          description: 'Used for pagination. The number of items to skip before starting to collect the result set, default is 0.'
          schema:
            type: integer
            minimum: 0
            default: 0
        - name: limit
          in: query
          description: 'Used for pagination. The maximum number of items to return, default is 20.'
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
        - name: sort
          in: query
          description: 'The field name to sort by (supported are: `startTime`, `title`, `distance` and `durationWithoutStops`). Default sort field is `startTime` and order is DESC. Prepend a `-` to order DESC: e.g. `title` vs. `-title`.'
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  pagination:
                    type: object
                    description: Pagination meta data.
                    properties:
                      total:
                        type: integer
                        format: int32
                      offset:
                        type: integer
                        format: int32
                      limit:
                        type: integer
                        format: int32
                    required:
                      - total
                      - offset
                      - limit
                  activitySummaries:
                    type: array
                    items:
                      $ref: '#/components/schemas/ActivitySummary'
                  links:
                    type: object
                    description: Generated links for pagination.
                    properties:
                      self:
                        type: string
                        format: uri
                      prev:
                        type: string
                        format: uri
                      next:
                        type: string
                        format: uri
                      last:
                        type: string
                        format: uri
                      first:
                        type: string
                        format: uri
                    required:
                      - self
                required:
                  - pagination
                  - activitySummaries
                  - links
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '500':
          $ref: '#/components/responses/500'
        default:
          $ref: '#/components/responses/default'
      security:
        - OIDC:
            - 'activity:summaries:read'
      servers:
        - url: 'https://api.bosch-ebike.com/activity/smart-system/v1'
          description: Production
  '/activities/{activityId}/details':
    get:
      tags:
        - Activities
      summary: Retrieve details of a single activity
      description: Returns a list of activity details for the given activityId associated with a user.
      operationId: get-activity-details
      parameters:
        - name: activityId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  activityDetails:
                    type: array
                    items:
                      $ref: '#/components/schemas/ActivityDetail'
                required:
                  - activityDetails
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
        default:
          $ref: '#/components/responses/default'
      security:
        - OIDC:
            - 'activity:details:read'
      servers:
        - url: 'https://api.bosch-ebike.com/activity/smart-system/v1'
          description: Production
tags:
  - name: Activities
components:
  securitySchemes:
    OIDC:
      type: oauth2
      description: |-
        Bosch Identity & Access Management

        **Offline Access:** Client applications may use [offline_access](https://openid.net/specs/openid-connect-core-1_0.html#OfflineAccess) tokens instead of refresh tokens. See the scope description below.
      flows:
        authorizationCode:
          refreshUrl: 'https://p9.authz.bosch.com/auth/realms/obc/protocol/openid-connect/token'
          authorizationUrl: 'https://p9.authz.bosch.com/auth/realms/obc/protocol/openid-connect/auth'
          scopes:
            'activity:summaries:read': Enables reading activity summaries.
            'activity:details:read': Enables reading activity details.
            offline_access: Use this optional scope to request an offline token instead of a refresh token. The client application is responsible for securely persisting the offline token. The offline token never expires as long as it is used for a refresh token action at least once every 180 days.
          tokenUrl: 'https://p9.authz.bosch.com/auth/realms/obc/protocol/openid-connect/token'
  responses:
    '400':
      description: Example response
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
    '401':
      description: Unauthorized
      content:
        text/plain:
          schema:
            type: string
          examples:
            access-token-expired:
              value: JWT is expired
            access-token-validation-failed:
              value: JWT verification fails
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
    '403':
      description: Forbidden
      content:
        text/plain:
          schema:
            type: string
          examples:
            access-token-missing:
              value: 'RBAC: access denied'
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
    '404':
      description: Example response
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
    '500':
      description: Internal Server Error
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
          examples:
            internal-server-error:
              value:
                detail: an unexpected error occured
                requestId: 798a1836ee1a4a39b9e43f6425135bbe
                type: /internal-server-error
    default:
      description: Example response
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
  schemas:
    ActivitySummary:
      type: object
      title: ActivitySummary
      properties:
        id:
          type: string
          format: uuid
        startTime:
          type: string
          description: Starting time of the activity.
          format: date-time
        endTime:
          type: string
          description: End time of the activity.
          format: date-time
        timeZone:
          type: string
          description: 'Timezone of start position, IANA.'
          example: Europe/Berlin
        durationWithoutStops:
          type: integer
          description: Duration in motion in seconds.
          format: int32
        title:
          type: string
          description: Name of the activity.
        bikeId:
          type: string
          description: Bike uuid for the trip.
          format: uuid
        startOdometer:
          type: integer
          description: Odometer at start of activity in meters.
          format: int32
        speed:
          type: object
          properties:
            average:
              type: number
              description: Average speed in km/h.
              format: float
            maximum:
              type: number
              description: Maximum speed in km/h.
              format: float
          required:
            - average
            - maximum
        distance:
          type: integer
          description: Odometer diff of activity in meters.
          format: int32
        cadence:
          type: object
          properties:
            average:
              type: number
              description: Average cadence in rpm.
              format: float
            maximum:
              type: number
              description: Maximum cadence in rpm.
              format: float
          required:
            - average
            - maximum
        riderPower:
          type: object
          properties:
            average:
              type: number
              description: Average rider power in watts.
              format: float
            maximum:
              type: number
              description: Maximum rider power in watts.
              format: float
          required:
            - average
            - maximum
        elevation:
          type: object
          properties:
            gain:
              type: integer
              description: 'Elevation gain in m, only available with Mobile.'
              format: int32
            loss:
              type: integer
              description: 'Elevation loss in m, only available with Mobile.'
              format: int32
          required:
            - gain
            - loss
        caloriesBurned:
          type: number
          format: float
      required:
        - id
        - startTime
        - endTime
        - timeZone
        - durationWithoutStops
        - bikeId
        - startOdometer
        - speed
        - distance
        - cadence
        - riderPower
        - elevation
    ActivityDetail:
      type: object
      title: ActivityDetail
      properties:
        distance:
          type: number
          description: Distance from start in meters.
          format: double
        altitude:
          type: number
          description: Altitude above sea level WGS84 in meters.
          format: float
        speed:
          type: number
          description: Speed in km/h.
          format: float
        cadence:
          type: number
          description: Cadence in rpm.
          format: float
        latitude:
          type: number
          description: 'Latitude in degrees, WGS84.'
          format: double
        longitude:
          type: number
          description: 'Longitude in degrees, WGS84.'
          format: double
        riderPower:
          type: number
          description: Rider power in watts.
          format: float
    Problem:
      type: object
      title: Problem
      properties:
        type:
          type: string
          description: |
            A URI reference that uniquely identifies the problem type only in the context of the provided API. Opposed to the specification in RFC-7807, it is neither recommended to be dereferenceable and point to a human-readable documentation nor globally unique for the problem type.
          format: uri-reference
          default: 'about:blank'
          example: /some/uri-reference
        title:
          type: string
          description: |
            A short summary of the problem type. Written in English and readable for engineers, usually not suited for non technical stakeholders and not localized.
          example: some title for the error situation
        status:
          type: integer
          description: |
            The HTTP status code generated by the origin server for this occurrence of the problem.
          format: int32
          minimum: 100
          exclusiveMaximum: true
          maximum: 600
        detail:
          type: string
          description: |
            A human readable explanation specific to this occurrence of the problem that is helpful to locate the problem and give advice on how to proceed. Written in English and readable for engineers, usually not suited for non technical stakeholders and not localized.
          example: some description for the error situation
        instance:
          type: string
          description: |
            A URI reference that identifies the specific occurrence of the problem, e.g. by adding a fragment identifier or sub-path to the problem type. May be used to locate the root of this problem in the source code.
          format: uri-reference
          example: /some/uri-reference#specific-occurrence-context
        requestId:
          type: string
          description: ID for this request.
          example: 075be661d3a4460b98dee5d66849dd5e
      required:
        - type
        - detail
        - requestId
security:
  - OIDC: []
